### ISSUE TITLE
[Push request] Internal testing and debugging source code of the Polyend Tracker's release firmware

### ISSUE THREAD

**Issue by egoshiner** [patois/RETracker#2]
**I have a copy of Polyend's internal source for the Tracker** (and their next device if you read the loads of documentation they include, NEARLY ENTIRELY IN ENGLISH, with only short release/change-notes in Polish.

_This_ is includes the extra files used to run this software off just open-source technology like Teensy 1.6 and some Arduino._ and will certainly make reverse engineering it easier.

**These files were not acquired by malicious means and their licensed for distribution (!!!)**

[SourceCode.zip](https://github.com/patois/RETracker/files/8254049/SourceCode.zip)
provided by JerzyHertz/EgoShiner/Aaron

**Comment by ambv** [comment]
Whatever the means to acquire the source code, it is not licensed for redistribution. We would kindly ask you to delete this issue and your fork. We don't oppose reverse-engineering efforts but the source code itself is our intellectual property.
